# Generated by Django 3.0.6 on 2020-05-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200518_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
